### ISSUE TITLE
Error: `make` failed with exit code: 2 - When installing jsreport-pdf-password.

### ISSUE THREAD

**Issue by visheshCuriousDev** [jsreport/jsreport-pdf-password#4]
I am always getting below error always and am unable to run the program itself.

`root@vishesh:/home/vishesh/cross# sudo npm i jsreport-pdf-password
> hummus@1.0.68 install /home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus
> node-pre-gyp install --fallback-to-build
node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/bin/node',
node-pre-gyp verb cli   '/home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.29
node-pre-gyp info using node@11.9.0 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus/binding/hummus.node" (not found)
node-pre-gyp http GET https://hummus.s3-us-west-2.amazonaws.com/hummus/v1.0.68/node-v67-linux-x64.tar.gz
node-pre-gyp http 404 https://hummus.s3-us-west-2.amazonaws.com/hummus/v1.0.68/node-v67-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download: https://hummus.s3-us-west-2.amazonaws.com/hummus/v1.0.68/node-v67-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for hummus@1.0.68 and node@11.9.0 (node-v67 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http Pre-built binary not available for your system, looked for https://hummus.s3-us-west-2.amazonaws.com/hummus/v1.0.68/node-v67-linux-x64.tar.gz 
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp ERR! Tried to download: https://hummus.s3-us-west-2.amazonaws.com/hummus/v1.0.68/node-v67-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for hummus@1.0.68 and node@11.9.0 (node-v67 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file 
node-pre-gyp verb command build [ 'rebuild' ]
make: Entering directory '/home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus/build'
  CXX(target) Release/obj.target/pdfwriter/src/deps/PDFWriter/AbstractContentContext.o
make: Entering directory '/home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus/build'
  CXX(target) Release/obj.target/pdfwriter/src/deps/PDFWriter/AbstractContentContext.o
rm:   CXX(target) Release/obj.target/pdfwriter/src/deps/PDFWriter/AbstractWrittenFont.o
cannot remove './Release/.deps/Release/obj.target/pdfwriter/src/deps/PDFWriter/AbstractContentContext.o.d.raw': No such file or directory
src/deps/PDFWriter/pdfwriter.target.mk:245: recipe for target 'Release/obj.target/pdfwriter/src/deps/PDFWriter/AbstractContentContext.o' failed
make: *** [Release/obj.target/pdfwriter/src/deps/PDFWriter/AbstractContentContext.o] Error 1
make: Leaving directory '/home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.15.0-46-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus/binding/hummus.node" "--module_name=hummus" "--module_path=/home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus/binding"
gyp ERR! cwd /home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus
gyp ERR! node -v v11.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus/binding/hummus.node --module_name=hummus --module_path=/home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Linux 4.15.0-46-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus
node-pre-gyp ERR! node -v v11.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus/binding/hummus.node --module_name=hummus --module_path=/home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus/binding' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hummus@1.0.68 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hummus@1.0.68 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-01T09_37_16_805Z-debug.log
root@vishesh:/home/vishesh/cross# ../src/deps/PDFWriter/AbstractWrittenFont.cpp:488:1: fatal error: opening dependency file ./Release/.deps/Release/obj.target/pdfwriter/src/deps/PDFWriter/AbstractWrittenFont.o.d.raw: No such file or directory
compilation terminated.
src/deps/PDFWriter/pdfwriter.target.mk:245: recipe for target 'Release/obj.target/pdfwriter/src/deps/PDFWriter/AbstractWrittenFont.o' failed
make: *** [Release/obj.target/pdfwriter/src/deps/PDFWriter/AbstractWrittenFont.o] Error 1
make: Leaving directory '/home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.15.0-46-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus/binding/hummus.node" "--module_name=hummus" "--module_path=/home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus/binding"
gyp ERR! cwd /home/vishesh/cross/node_modules/jsreport-pdf-password/node_modules/hummus
gyp ERR! node -v v11.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

`

My node version: v11.9.0

**Comment by bjrmatos** [comment]
hi! it looks like some internal dependency ([hummus package](https://github.com/galkahana/HummusJS)) can not be installed because your node version, maybe if you switch to node v10 and try to install it will work
